// WHAP "Most Significant Locations in the World" — geocoded for MapDrill.
// category: "political" | "geographical"
// Coordinates are representative points (river = a well-known stretch,
// range = its core, sea/region = its center). Tweak any lat/lng freely.
window.PLACES = [

  // ========================= POLITICAL =========================
  { name: "United States", category: "political", lat: 39.5, lng: -98.35 },
  { name: "Canada", category: "political", lat: 56.13, lng: -106.35 },
  { name: "Mexico", category: "political", lat: 23.63, lng: -102.55 },
  { name: "Brazil", category: "political", lat: -14.24, lng: -51.93 },
  { name: "Panama", category: "political", lat: 8.54, lng: -80.78 },
  { name: "Cuba", category: "political", lat: 21.52, lng: -79.50 },
  { name: "Dominican Republic / Haiti", category: "political", lat: 18.93, lng: -71.05 },
  { name: "United Kingdom", category: "political", lat: 54.00, lng: -2.50 },
  { name: "Ireland", category: "political", lat: 53.35, lng: -8.00 },
  { name: "France", category: "political", lat: 46.23, lng: 2.21 },
  { name: "Portugal", category: "political", lat: 39.50, lng: -8.00 },
  { name: "Spain", category: "political", lat: 40.20, lng: -3.70 },
  { name: "Germany", category: "political", lat: 51.17, lng: 10.45 },
  { name: "Russia", category: "political", lat: 61.50, lng: 100.00 },
  { name: "Switzerland", category: "political", lat: 46.80, lng: 8.23 },
  { name: "Italy", category: "political", lat: 42.50, lng: 12.50 },
  { name: "Egypt", category: "political", lat: 26.82, lng: 30.80 },
  { name: "South Africa", category: "political", lat: -30.56, lng: 22.94 },
  { name: "Mecca, Saudi Arabia", category: "political", lat: 21.42, lng: 39.83 },
  { name: "Jerusalem, Israel", category: "political", lat: 31.78, lng: 35.22 },
  { name: "Iran", category: "political", lat: 32.43, lng: 53.69 },
  { name: "Iraq", category: "political", lat: 33.22, lng: 43.68 },
  { name: "Afghanistan", category: "political", lat: 33.94, lng: 67.71 },
  { name: "Syria", category: "political", lat: 34.80, lng: 38.00 },
  { name: "Pakistan", category: "political", lat: 30.38, lng: 69.35 },
  { name: "India", category: "political", lat: 22.00, lng: 79.00 },
  { name: "North Korea", category: "political", lat: 40.34, lng: 127.51 },
  { name: "South Korea", category: "political", lat: 36.50, lng: 127.85 },
  { name: "Japan", category: "political", lat: 36.20, lng: 138.25 },
  { name: "China", category: "political", lat: 35.86, lng: 104.20 },
  { name: "Vietnam", category: "political", lat: 14.06, lng: 108.28 },

  // ==================== CONTINENTS & OCEANS ====================
  { name: "North America", category: "geographical", lat: 48.00, lng: -100.00 },
  { name: "South America", category: "geographical", lat: -15.00, lng: -60.00 },
  { name: "Europe", category: "geographical", lat: 52.00, lng: 18.00 },
  { name: "Africa", category: "geographical", lat: 2.00, lng: 22.00 },
  { name: "Asia", category: "geographical", lat: 45.00, lng: 90.00 },
  { name: "Australia", category: "geographical", lat: -25.27, lng: 133.78 },
  { name: "Antarctica", category: "geographical", lat: -75.00, lng: 0.00 },
  { name: "Pacific Ocean", category: "geographical", lat: 0.00, lng: -150.00 },
  { name: "Atlantic Ocean", category: "geographical", lat: 5.00, lng: -30.00 },
  { name: "Indian Ocean", category: "geographical", lat: -25.00, lng: 78.00 },
  { name: "Arctic Ocean", category: "geographical", lat: 80.00, lng: 0.00 },

  // ================= PHYSICAL / GEOGRAPHICAL ==================
  { name: "Mississippi River", category: "geographical", lat: 32.30, lng: -90.90 },
  { name: "Rocky Mountains", category: "geographical", lat: 40.00, lng: -106.00 },
  { name: "Appalachian Mountains", category: "geographical", lat: 37.50, lng: -81.50 },
  { name: "Rio Grande", category: "geographical", lat: 29.50, lng: -101.00 },
  { name: "Colorado River", category: "geographical", lat: 36.10, lng: -112.10 },
  { name: "St. Lawrence River", category: "geographical", lat: 47.20, lng: -70.50 },
  { name: "Gulf of Mexico", category: "geographical", lat: 25.00, lng: -90.00 },
  { name: "Panama Canal", category: "geographical", lat: 9.08, lng: -79.68 },
  { name: "Caribbean Sea", category: "geographical", lat: 15.00, lng: -75.00 },
  { name: "Andes Mountains", category: "geographical", lat: -18.00, lng: -69.00 },
  { name: "Amazon River", category: "geographical", lat: -3.40, lng: -60.00 },
  { name: "Pyrenees Mountains", category: "geographical", lat: 42.60, lng: 1.00 },
  { name: "Alps", category: "geographical", lat: 46.50, lng: 9.50 },
  { name: "Ural Mountains", category: "geographical", lat: 60.00, lng: 59.00 },
  { name: "Danube River", category: "geographical", lat: 44.80, lng: 20.50 },
  { name: "English Channel", category: "geographical", lat: 50.20, lng: -0.70 },
  { name: "Strait of Gibraltar", category: "geographical", lat: 35.95, lng: -5.60 },
  { name: "Caspian Sea", category: "geographical", lat: 41.50, lng: 50.50 },
  { name: "Black Sea", category: "geographical", lat: 43.40, lng: 34.30 },
  { name: "Mediterranean Sea", category: "geographical", lat: 35.00, lng: 18.00 },
  { name: "Sahara Desert", category: "geographical", lat: 23.00, lng: 13.00 },
  { name: "Red Sea", category: "geographical", lat: 20.30, lng: 38.00 },
  { name: "Suez Canal", category: "geographical", lat: 30.50, lng: 32.35 },
  { name: "Nile River", category: "geographical", lat: 26.00, lng: 32.00 },
  { name: "Niger River", category: "geographical", lat: 16.00, lng: -1.00 },
  { name: "Congo River", category: "geographical", lat: -1.50, lng: 18.00 },
  { name: "Arabian Sea", category: "geographical", lat: 15.00, lng: 65.00 },
  { name: "Persian Gulf", category: "geographical", lat: 27.00, lng: 51.00 },
  { name: "Hindu Kush", category: "geographical", lat: 36.00, lng: 71.50 },
  { name: "Tigris / Euphrates Rivers", category: "geographical", lat: 33.00, lng: 44.00 },
  { name: "Bay of Bengal", category: "geographical", lat: 15.00, lng: 88.00 },
  { name: "Strait of Malacca", category: "geographical", lat: 2.50, lng: 101.00 },
  { name: "Yangtze River", category: "geographical", lat: 30.60, lng: 112.00 },
  { name: "Huang He River (Yellow River)", category: "geographical", lat: 36.00, lng: 116.00 },
  { name: "South China Sea", category: "geographical", lat: 13.00, lng: 114.00 },
  { name: "Himalayas", category: "geographical", lat: 28.60, lng: 83.93 },
  { name: "Ganges River", category: "geographical", lat: 25.30, lng: 85.00 },
  { name: "Indus River", category: "geographical", lat: 27.00, lng: 68.30 },
  { name: "Bering Strait", category: "geographical", lat: 65.70, lng: -169.00 },
  { name: "Outback", category: "geographical", lat: -24.00, lng: 133.00 },

  // ========================= REGIONS ==========================
  { name: "Region of Latin America", category: "geographical", lat: 0.00, lng: -70.00 },
  { name: "Region of the Caribbean", category: "geographical", lat: 16.00, lng: -75.00 },
  { name: "Region of Central Asia", category: "geographical", lat: 43.00, lng: 65.00 },
  { name: "Region of Middle East", category: "geographical", lat: 29.00, lng: 45.00 },
  { name: "Region of North Africa", category: "geographical", lat: 27.00, lng: 15.00 },
  { name: "Region of West Africa", category: "geographical", lat: 12.00, lng: -3.00 },
  { name: "Region of East Africa", category: "geographical", lat: 2.00, lng: 37.00 },
  { name: "Region of Central Africa", category: "geographical", lat: 2.00, lng: 20.00 },
  { name: "Region of Southern Africa", category: "geographical", lat: -25.00, lng: 25.00 },
  { name: "Region of South Asia", category: "geographical", lat: 20.00, lng: 80.00 },
  { name: "Region of East Asia", category: "geographical", lat: 37.00, lng: 110.00 },
  { name: "Region of Southeast Asia", category: "geographical", lat: 5.00, lng: 110.00 }
];
